export const userActionTypes = {
  SET_REGISTER_VALIDATION: 'SET_REGISTER_VALIDATION',
  SET_LOGIN_VALIDATION: 'SET_LOGIN_VALIDATION',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CLEAN_CURRENT_USER: 'CLEAN_CURRENT_USER',
};
