export const REGISTER_VALIDATION_SET = 'REGISTER_VALIDATION_SET';
export const LOGIN_VALIDATION_SET = 'LOGIN_VALIDATION_SET';

export const USER_REGISTER_REQUESTED = 'USER_REGISTER_REQUESTED';
export const USER_REGISTER_SUCCEEDED = 'USER_REGISTER_SUCCEEDED';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const CURRENT_USER_SET = 'CURRENT_USER_SET';
export const CURRENT_USER_UNSET = 'CURRENT_USER_UNSET';
